### ISSUE TITLE
失效了,大佬能更新一下吗?

### ISSUE THREAD

**Issue by hunter8605** [left1101/sign_iqiyi#1]
程序执行提示:
Traceback (most recent call last):
  File "app.py", line 89, in <module>
    main_handler()
  File "app.py", line 83, in main_handler
    sign_iqiyi()
  File "app.py", line 59, in sign_iqiyi
    str=str["data"]["acquireGiftList"][0]
KeyError: 'data'

通知提示:

爱奇艺签到通知

{"code":"VIP_EXPIRED","msg":"用户已经过期"}

**Comment by left1101** [comment]
您好，您把
# str=json.loads(sign)
# str=str["data"]["acquireGiftList"][0]

# sign_txsp()
这三行注释了就可以了，代码没问题

**Comment by hunter8605** [comment]
好的，明天测试一下签到和抽奖功能，另外请问抽奖能增加积分抽奖功能吗？

**Comment by left1101** [comment]
不好意思，最近没时间哈
